name: CMake Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    # Ensure Ninja and Clang are available
    - name: Install Ninja
      run: choco install ninja

    - name: Install LLVM Clang
      run: choco install clang

    - name: Configure CMake
      # We add -G "Ninja" AND use CLANG FFS
      run: cmake -DCMAKE_CXX_COMPILER=clang++ -G "Ninja" -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}


    # Extracting .exe
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: null-widget-release
        path: ${{github.workspace}}/build/null-widget.exe
